experiment:
    name: "audio_cosloss"

model:
    type: "rqvae" # mhead
    # type: "mhead"
    input_feature_size: 2048
    num_head: 8
    codebook_dim: 256
    codebook_size: 256
    pretrain_embedding_path: None
    encoder_mlp_size: [1024, 512] # [512, 256, 128]
    decoder_mlp_size: [512, 1024] # [512, 256, 128]
    shared_codebook: False
    save_dir: '/data/phd/qinsizhong/emb_vqvae/model'

wandb:
    is_use: True
    project: 'video-frame-vae'

infer:
    infer_path: '/data/phd/qinsizhong/emb_vqvae/infer/photoid2index.txt'
    
trainer:
    learning_rate: 1e-3    
    min_lr: 2e-5
    weight_decay: 0.0001
    max_epoch: 50
    plot_every: 100
    save_every: 10
    warmup: 0
    loss_type: 'cos' # [L1, L2]
    recon_weight: 1.
    commit_weight: 0.

load:
    model_path: '/data/phd/qinsizhong/emb_vqvae/model/rqvae_L2loss_rqvae_CBsize256_CBdim16_CBhead8_lr_1.00e-03_2025-07-01-20:58:54'
    epoch_id: 99


dataset:
    data_root: '/data/phd/qinsizhong/emb_vqvae/data'
    batch_size: 8192  # train batchsize; test batchsize is fixed as 8192
    num_workers: 8
    # train_file: '/data/phd/qinsizhong/ad_edit_inference/ex_incycle2/frame_db_train.pt'
    # test_file: '/data/phd/qinsizhong/ad_edit_inference/ex_incycle2/frame_db_eval.pt'
    # infer_file: '/data/phd/qinsizhong/ad_edit_inference/ex_incycle2/frame_db_eval.pt'
    train_file: '/data/phd/qinsizhong/ad_edit_inference/ex_incycle2/audio_db_train.pt'
    test_file: '/data/phd/qinsizhong/ad_edit_inference/ex_incycle2/audio_db_eval.pt'
    infer_file: '/data/phd/qinsizhong/ad_edit_inference/ex_incycle2/audio_db_eval.pt'