experiment:
  name: rqvae_L2loss
model:
  type: rqvae
  input_feature_size: 128
  num_head: 24
  codebook_dim: 384
  codebook_size: 256
  pretrain_embedding_path: None
  encoder_mlp_size:
  - 256
  - 256
  decoder_mlp_size:
  - 256
  - 256
  shared_codebook: False
  save_dir: /data/phd/qinsizhong/emb_vqvae/model
wandb:
  is_use: False
  project: video-frame-vae
infer:
  infer_path: /data/phd/qinsizhong/emb_vqvae/infer/photoid2index.txt
trainer:
  learning_rate: 0.001
  min_lr: 2.0e-05
  weight_decay: 0.0001
  max_epoch: 100
  plot_every: 100
  save_every: 10
  warmup: 0
  loss_type: cos
  recon_weight: 1.0
  commit_weight: 0.0
load:
  model_path: model/rqvae_cosloss_rqvae_CBsize256_CBdim16_CBhead24_lr_1.00e-03_2025-07-03-21:16:19
  epoch_id: 99
dataset:
  data_root: /data/phd/qinsizhong/emb_vqvae/data
  batch_size: 2048
  num_workers: 8
  train_file: train_9000.pt
  test_file: test_others.pt
  infer_file: test_others.pt
