# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import tools.common.vocal_split.Vocal_split_pb2 as Vocal__split__pb2


class VocalSplitServingStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetSplitVocal = channel.unary_unary(
        '/ad.creative.model.vocal_split.VocalSplitServing/GetSplitVocal',
        request_serializer=Vocal__split__pb2.VocalSplitRequest.SerializeToString,
        response_deserializer=Vocal__split__pb2.VocalSplitResponse.FromString,
        )


class VocalSplitServingServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetSplitVocal(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_VocalSplitServingServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetSplitVocal': grpc.unary_unary_rpc_method_handler(
          servicer.GetSplitVocal,
          request_deserializer=Vocal__split__pb2.VocalSplitRequest.FromString,
          response_serializer=Vocal__split__pb2.VocalSplitResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'ad.creative.model.vocal_split.VocalSplitServing', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
