# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Vocal_split.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Vocal_split.proto',
  package='ad.creative.model.vocal_split',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x11Vocal_split.proto\x12\x1d\x61\x64.creative.model.vocal_split\"X\n\x11VocalSplitRequest\x12\x43\n\x0evocal_blob_key\x18\x01 \x01(\x0b\x32+.ad.creative.model.vocal_split.BlobStoreKey\"6\n\x0c\x42lobStoreKey\x12\n\n\x02\x64\x62\x18\x01 \x01(\t\x12\r\n\x05table\x18\x02 \x01(\t\x12\x0b\n\x03key\x18\x03 \x01(\t\"s\n\x12VocalSplitResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x12\n\nfailreason\x18\x02 \x01(\t\x12\x39\n\x03res\x18\x03 \x01(\x0b\x32,.ad.creative.model.vocal_split.VocalSplitRes\"\x94\x01\n\rVocalSplitRes\x12?\n\nvocal_part\x18\x01 \x01(\x0b\x32+.ad.creative.model.vocal_split.BlobStoreKey\x12\x42\n\rno_vocal_part\x18\x02 \x01(\x0b\x32+.ad.creative.model.vocal_split.BlobStoreKey2\x89\x01\n\x11VocalSplitServing\x12t\n\rGetSplitVocal\x12\x30.ad.creative.model.vocal_split.VocalSplitRequest\x1a\x31.ad.creative.model.vocal_split.VocalSplitResponseb\x06proto3')
)




_VOCALSPLITREQUEST = _descriptor.Descriptor(
  name='VocalSplitRequest',
  full_name='ad.creative.model.vocal_split.VocalSplitRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='vocal_blob_key', full_name='ad.creative.model.vocal_split.VocalSplitRequest.vocal_blob_key', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=52,
  serialized_end=140,
)


_BLOBSTOREKEY = _descriptor.Descriptor(
  name='BlobStoreKey',
  full_name='ad.creative.model.vocal_split.BlobStoreKey',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='db', full_name='ad.creative.model.vocal_split.BlobStoreKey.db', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='table', full_name='ad.creative.model.vocal_split.BlobStoreKey.table', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='key', full_name='ad.creative.model.vocal_split.BlobStoreKey.key', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=142,
  serialized_end=196,
)


_VOCALSPLITRESPONSE = _descriptor.Descriptor(
  name='VocalSplitResponse',
  full_name='ad.creative.model.vocal_split.VocalSplitResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='ad.creative.model.vocal_split.VocalSplitResponse.status', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='failreason', full_name='ad.creative.model.vocal_split.VocalSplitResponse.failreason', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='res', full_name='ad.creative.model.vocal_split.VocalSplitResponse.res', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=198,
  serialized_end=313,
)


_VOCALSPLITRES = _descriptor.Descriptor(
  name='VocalSplitRes',
  full_name='ad.creative.model.vocal_split.VocalSplitRes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='vocal_part', full_name='ad.creative.model.vocal_split.VocalSplitRes.vocal_part', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='no_vocal_part', full_name='ad.creative.model.vocal_split.VocalSplitRes.no_vocal_part', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=316,
  serialized_end=464,
)

_VOCALSPLITREQUEST.fields_by_name['vocal_blob_key'].message_type = _BLOBSTOREKEY
_VOCALSPLITRESPONSE.fields_by_name['res'].message_type = _VOCALSPLITRES
_VOCALSPLITRES.fields_by_name['vocal_part'].message_type = _BLOBSTOREKEY
_VOCALSPLITRES.fields_by_name['no_vocal_part'].message_type = _BLOBSTOREKEY
DESCRIPTOR.message_types_by_name['VocalSplitRequest'] = _VOCALSPLITREQUEST
DESCRIPTOR.message_types_by_name['BlobStoreKey'] = _BLOBSTOREKEY
DESCRIPTOR.message_types_by_name['VocalSplitResponse'] = _VOCALSPLITRESPONSE
DESCRIPTOR.message_types_by_name['VocalSplitRes'] = _VOCALSPLITRES
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

VocalSplitRequest = _reflection.GeneratedProtocolMessageType('VocalSplitRequest', (_message.Message,), dict(
  DESCRIPTOR = _VOCALSPLITREQUEST,
  __module__ = 'Vocal_split_pb2'
  # @@protoc_insertion_point(class_scope:ad.creative.model.vocal_split.VocalSplitRequest)
  ))
_sym_db.RegisterMessage(VocalSplitRequest)

BlobStoreKey = _reflection.GeneratedProtocolMessageType('BlobStoreKey', (_message.Message,), dict(
  DESCRIPTOR = _BLOBSTOREKEY,
  __module__ = 'Vocal_split_pb2'
  # @@protoc_insertion_point(class_scope:ad.creative.model.vocal_split.BlobStoreKey)
  ))
_sym_db.RegisterMessage(BlobStoreKey)

VocalSplitResponse = _reflection.GeneratedProtocolMessageType('VocalSplitResponse', (_message.Message,), dict(
  DESCRIPTOR = _VOCALSPLITRESPONSE,
  __module__ = 'Vocal_split_pb2'
  # @@protoc_insertion_point(class_scope:ad.creative.model.vocal_split.VocalSplitResponse)
  ))
_sym_db.RegisterMessage(VocalSplitResponse)

VocalSplitRes = _reflection.GeneratedProtocolMessageType('VocalSplitRes', (_message.Message,), dict(
  DESCRIPTOR = _VOCALSPLITRES,
  __module__ = 'Vocal_split_pb2'
  # @@protoc_insertion_point(class_scope:ad.creative.model.vocal_split.VocalSplitRes)
  ))
_sym_db.RegisterMessage(VocalSplitRes)



_VOCALSPLITSERVING = _descriptor.ServiceDescriptor(
  name='VocalSplitServing',
  full_name='ad.creative.model.vocal_split.VocalSplitServing',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=467,
  serialized_end=604,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetSplitVocal',
    full_name='ad.creative.model.vocal_split.VocalSplitServing.GetSplitVocal',
    index=0,
    containing_service=None,
    input_type=_VOCALSPLITREQUEST,
    output_type=_VOCALSPLITRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_VOCALSPLITSERVING)

DESCRIPTOR.services_by_name['VocalSplitServing'] = _VOCALSPLITSERVING

# @@protoc_insertion_point(module_scope)
